services:
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

      - MODEL_DIR=/models
      - DATA_DIR=/data

      - API_PORT=${API_PORT}
      - TFS_PORT=${TFS_PORT}
      - LORCANA_PORT=${LORCANA_PORT}
      - POKEMON_PORT=${POKEMON_PORT}
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./models:/models:ro
      - ./data:/data:ro
      - ./.env:/app/.env
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 16g
        reservations:
          devices:
              capabilities: [gpu]
    restart: unless-stopped
    container_name: api

  tfs-lorcana:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "${LORCANA_PORT}:8501"
    volumes:
      - ./saved_models/lorcana/:/models/lorcana/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/lorcana/tfs.config
      --model_config_file_poll_wait_seconds=60
    restart: unless-stopped
    container_name: tfs-lorcana

  tfs-pokemon:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "${POKEMON_PORT}:8501"
    volumes:
      - ./saved_models/pokemon/:/models/pokemon/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/pokemon/tfs.config
      --model_config_file_poll_wait_seconds=60
    restart: unless-stopped
    container_name: tfs-pokemon

