services:
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

      - MODEL_DIR=/keras_models
      - DATA_DIR=/data
      - SAVED_MODEL_DIR=/saved_models

      - API_PORT=${API_PORT}
      - TFS_PORT=${TFS_PORT}
      - LORCANA_PORT=${LORCANA_PORT}
      - POKEMON_PORT=${POKEMON_PORT}

      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./keras_models:/keras_models
      - ./saved_models:/saved_models
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    container_name: api

  tfs-lorcana:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${LORCANA_PORT}:8501"
    volumes:
      - ./saved_models/lorcana/:/models/lorcana/
      - ./batching_parameters.txt:/batching_parameters.txt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/lorcana/tfs.config
      --model_config_file_poll_wait_seconds=60
      --enable_batching
      --batching_parameters_file=/batching_parameters.txt
    restart: unless-stopped
    container_name: tfs-lorcana

  tfs-pokemon:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${POKEMON_PORT}:8501"
    volumes:
      - ./saved_models/pokemon/:/models/pokemon/
      - ./batching_parameters.txt:/batching_parameters.txt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/pokemon/tfs.config
      --model_config_file_poll_wait_seconds=60
      --enable_batching
      --batching_parameters_file=/batching_parameters.txt
    restart: unless-stopped
    container_name: tfs-pokemon

