services:
  card-id:
    build: .
    image: card-id-service:dev
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models:ro
      - ./data:/data:ro
    environment:
      - MODEL_DIR=/models
      - PORT=8000
      - WEB_CONCURRENCY=1
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

