services:
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/models:ro
      - ./data:/data:ro
    environment:
      - MODEL_DIR=/models
      - PORT=5000
      - WEB_CONCURRENCY=1
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: api
