services:
  training:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file: 
      - path: ./.env.development
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TF_CPP_MIN_LOG_LEVEL=1
      - TF_CUDNN_DETERMINISTIC=true
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./:/harmony
    runtime: nvidia
    restart: unless-stopped
    container_name: training 
    stdin_open: true
    tty: true
    command: bash

  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - path: ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./keras_models:/keras_models
      - ./saved_models:/saved_models
      - ./data:/data
      - ./config:/config
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    container_name: api

  tfs-lorcana:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${LORCANA_PORT}:8501"
    volumes:
      - ./saved_models/lorcana/:/models/lorcana/
      - ./batching_parameters.txt:/batching_parameters.txt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/lorcana/tfs.config
      --model_config_file_poll_wait_seconds=60
      --enable_batching
      --batching_parameters_file=/batching_parameters.txt
    restart: unless-stopped
    container_name: tfs-lorcana

  tfs-pokemon:
    image: tensorflow/serving:latest-gpu
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    ports:
      - "${POKEMON_PORT}:8501"
    volumes:
      - ./saved_models/pokemon/:/models/pokemon/
      - ./batching_parameters.txt:/batching_parameters.txt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      --model_config_file=/models/pokemon/tfs.config
      --model_config_file_poll_wait_seconds=60
      --enable_batching
      --batching_parameters_file=/batching_parameters.txt
    restart: unless-stopped
    container_name: tfs-pokemon

