[m0]
	batch_size=64
	model_name='CnnModelClassic15Mini'
	img_height=437
	img_width=313
	num_unique_classes=994
	augment_multiplication=500
	learning_rate=0.00005
	beta_1=0.9
	beta_2=0.999
	label_smoothing=0.05
	stopping_threshold=98
	is_final=true


